#!/bin/bash

# Simple shell script to manage monitor's power modes.
# Copyright (c) 2007  Viacheslav Chumushuk <voice@root.ua>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


function print_usage
{
    echo "Usage: `basename $0` standby|suspend|off"
}

if [[ $# -ne 1 ]]
then
    print_usage
    exit 0
fi

if [[ $1 == "standby" ]] || [[ $1 == "suspend" ]] || [[ $1 == "off" ]]
then
    sleep 1s
    xset dpms force $1
else
    print_usage
    exit 1
fi

