#!/bin/bash

# Simple shell script for interacive adding files to svn control.
# Copyright (c) 2010 Viacheslav Chumushuk <voice@root.ua>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


svn status | grep '^?' | sed 's/^?\s*//' | while read filename
do
    echo -n "Add $filename ander revision control? [y/N]"
    read answer < /dev/tty
  
    echo $answer | grep -i '^y' > /dev/null

    if [ $? -eq 0 ]
    then
	svn add "$filename"
    fi
done
